assets {
  asset_type: AH_CENTERS
  asset_path: "drive/MyDrive/Colab Notebooks/two_stage_rec_2/searcher/ah_codebook.pb"
}
assets {
  asset_type: PARTITIONER
  asset_path: "drive/MyDrive/Colab Notebooks/two_stage_rec_2/searcher/serialized_partitioner.pb"
}
assets {
  asset_type: TOKENIZATION_NPY
  asset_path: "drive/MyDrive/Colab Notebooks/two_stage_rec_2/searcher/datapoint_to_token.npy"
}
assets {
  asset_type: AH_DATASET_NPY
  asset_path: "drive/MyDrive/Colab Notebooks/two_stage_rec_2/searcher/hashed_dataset.npy"
}
assets {
  asset_type: DATASET_NPY
  asset_path: "drive/MyDrive/Colab Notebooks/two_stage_rec_2/searcher/dataset.npy"
}
